In [1]:
import math
import time
import numpy as np
from numba import vectorize, float64,guvectorize

In [2]:
def elapsed_time(function):
    # get starting time
    start = time.time()

    print(function)

    # get time taken to run the for loop code 
    elapsed_time = (time.time() - start)
    
    return elapsed_time

# function 1

In [3]:
def vectorize(coord):

    t = np.array([[math.cos(coord[0])*math.sin(coord[1]), math.sin(coord[0])*math.sin(coord[1]), math.cos(coord[1])],\
    [-math.sin(coord[0]), math.cos(coord[0]),0],\
    [-math.cos(coord[0])*math.cos(coord[1]), -math.sin(coord[0])*math.cos(coord[1]),math.sin(coord[1])]])
    #
    #
    B = np.array([[t[0,0]*t[0,0], t[0][1]*t[0,1], t[0,2]*t[0,2], 2*t[0,0]*t[0,1], 2*t[0,0]*t[0,2], 2*t[0,2]*t[0,1]],\
    [t[1,0]*t[1,0], t[1,1]*t[1,1], t[1,2]*t[1,2], 2*t[1,0]*t[1,1], 2*t[1,0]*t[1,2], 2*t[1,2]*t[1,1]],\
    [t[2,0]*t[2,0], t[2,1]*t[2,1], t[2,2]*t[2,2], 2*t[2,0]*t[2,1], 2*t[2,0]*t[2,2], 2*t[2,2]*t[2,1]],\
    [t[0,0]*t[1,0], t[0,1]*t[1,1], t[0,2]*t[1,2], t[0,0]*t[1,1]+t[0,1]*t[1,0], t[0,2]*t[1,0]+t[0,0]*t[1,2], t[0,1]*t[1,2]+t[0,2]*t[1,1]],\
    [t[0,0]*t[2,0], t[0,1]*t[2,1], t[0,2]*t[2,2], t[0,0]*t[2,1]+t[0,1]*t[2,0], t[0,2]*t[2,0]+t[0,0]*t[2,2], t[0,2]*t[2,1]+t[0,1]*t[2,2]],\
    [t[1,0]*t[2,0], t[1,1]*t[2,1], t[1,2]*t[2,2], t[1,0]*t[2,1]+t[1,1]*t[2,0], t[1,2]*t[2,0]+t[1,0]*t[2,2], t[1,1]*t[2,2]+t[1,2]*t[2,1]]])

    return B
def TransformField(C, alpha, beta, flag):
    
    B = np.apply_along_axis(vectorize, 1, zip(alpha,beta))
    #
    #

    A = np.zeros((len(alpha),C.shape[0],6))
    G = np.zeros_like(C)
    #
    #        
    G[:,0:3] = C[:,0:3] ###

    if np.array(flag) == np.array('strain'):
        G[:,3:6] = C[:,3:6]/2.0 ####
    else:
        G[:,3:6] = C[:,3:6] ####

    A = np.dot(B,G.T) #####

    #
    if np.array(flag) == np.array('strain'):
        A[:,3:6] = A[:,3:6]*2.0 #####

    return A[:,:,:]

In [4]:
#v_TransformField = np.vectorize(TransformField)

In [5]:
C=np.array([[1,2,3,4,5,6],[0,1,0,0,0,0]])
alpha =  np.arange(0,185,5)
beta = np.arange(0,185,5)
flag ='strain'

In [6]:
vectorize

<function __main__.vectorize>

In [7]:
oldStress_Table = np.array([])###
oldStrain_Table = np.array([])###
for frame in range(10):
    stressN = 10
    strainN = 10

    stressTemp = np.zeros(6) ###
    strainTemp = np.zeros(6) ###

    stressN_data = np.array([1,2,3,4,5,6])
    strainN_data = np.array([0,1,0,0,0,0])

    stressTemp[:] = stressN_data[:]
    strainTemp[:] = strainN_data[:]

    oldStress_Table = np.append(oldStress_Table,stressTemp)###
    oldStrain_Table = np.append(oldStrain_Table,strainTemp)###

###C
oldStress_Table = oldStress_Table.reshape(10,6)###
oldStrain_Table = oldStrain_Table.reshape(10,6)###


In [8]:
C = oldStrain_Table
oldStrain_Table
C[0,0]=10

In [9]:
C[np.where(C == np.max(C))]=1000
C

array([[1000.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.],
       [   0.,    1.,    0.,    0.,    0.,    0.]])

In [30]:
np.max(C,axis=1)
o = np.array([],dtype=np.int)
print o.dtype

int32


In [11]:
ALPHA = np.arange(0,185,5)
#BETA = [0, 10, 20, 30, 40, 50,60, 70,80,90,100,110,120,130,140,150,160,170]
BETA = np.arange(0,185,5)
#
xx, yy = np.meshgrid(ALPHA, BETA)
ALPHA = yy.ravel() # 1d array of all combinations
BETA = xx.ravel() # 1d array of all combinations
ALPHA,BETA

(array([  0,   0,   0, ..., 180, 180, 180]),
 array([  0,   5,  10, ..., 170, 175, 180]))

In [13]:
coord = np.zeros((len(ALPHA),2))
coord[:,0] = ALPHA[:]
coord[:,1] = BETA[:]

In [14]:

coord

array([[  0.,   0.],
       [  0.,   5.],
       [  0.,  10.],
       ...,
       [180., 170.],
       [180., 175.],
       [180., 180.]])

In [15]:
a = [1, 2]
for index, x in np.ndenumerate(a):
    print(index, x)
a[index]

((0L,), 1)
((1L,), 2)


TypeError: list indices must be integers, not tuple

In [73]:
a = np.arange(6)
b = np.array([0,3,6,4,20,7])
np.isin(b, a)
node_list = np.zeros(12,dtype=np.int)

In [74]:
a = np.where([a==2*np.ones(6)])
a

(array([0], dtype=int64), array([2], dtype=int64))

In [75]:
c =np.where(a == True*np.ones(6))
c

(array([], dtype=int64), array([], dtype=int64))

In [50]:
mask = np.array([i in [0] for item in b])
mask

array([False, False, False, False, False, False])

In [51]:
mask =np.array([item in b for item in a])
mask

array([ True])

In [52]:
node_id =np.where(mask == True)
node_id

(array([0], dtype=int64),)

In [37]:
a = np.arange(4)
c = np.where(2== a)
d = np.where(a ==2)
a = np.array([1,2,3,0,0,2,0,2])
a[np.nonzero(a)]

array([1, 2, 3, 2, 2])

In [33]:
for (i,j) in zip(a,b):
    print('Node	'+str(j)+' has internal id	'+str(i))

Node	1 has internal id	0
Node	3 has internal id	1
Node	6 has internal id	2
Node	4 has internal id	3
Node	20 has internal id	4
Node	7 has internal id	5


In [25]:
g =TransformField(C, alpha, beta, flag)

In [198]:
sx =A[:,:,0] 
j = np.max(sx,axis=1)
k = np.arange(3)


In [202]:
j[np.where(k>1)] = k[np.where(k>1)]
(k+j)[np.where(k+j) >= 0]=0

In [204]:
k,j

(array([0, 1, 2]), array([3.49018843, 5.48677006, 2.        ]))

In [203]:
k+j

array([3.49018843, 6.48677006, 4.        ])

In [178]:

o=np.max(sx,axis=1)

In [41]:
k=np.where(o>3)
o[k]= o[k]/100.
o

NameError: name 'o' is not defined

In [250]:
coord  =np.array([[1,10],[1,6],[2,3]])
t_vect = np.zeros((3,3,3),dtype=np.float)
for i in range(3):
		t_vect[i,:,:] = np.array([[math.cos(coord[i,0])*math.sin(coord[i,1]), math.sin(coord[i,0])*math.sin(coord[i,1]), math.cos(coord[i,1])],\
		[-math.sin(coord[i,0]), math.cos(coord[i,0]),0],\
		[-math.cos(coord[i,0])*math.cos(coord[i,1]), -math.sin(coord[i,0])*math.cos(coord[i,1]),math.sin(coord[i,1])]])

In [252]:
t_vect

array([[[-0.29393586, -0.45777798, -0.83907153],
        [-0.84147098,  0.54030231,  0.        ],
        [ 0.45335228,  0.70605435, -0.54402111]],

       [[-0.15096884, -0.23512003,  0.96017029],
        [-0.84147098,  0.54030231,  0.        ],
        [-0.51878222, -0.80795544, -0.2794155 ]],

       [[-0.05872664,  0.12832006, -0.9899925 ],
        [-0.90929743, -0.41614684,  0.        ],
        [-0.41198225,  0.90019763,  0.14112001]]])

In [248]:
a=np.array([1,10])
b=np.array([[1,10],[1,6]])
def ok(k):
    
    t=np.array([[np.cos(k[:,0]),k[:,1]],[np.cos(k[:,0]),k[:,1]]])

    return t
    
#=np.array([[t[0],t[0]],[t[1],t[1]]])
#t = np.zeros((2,2,2,2))
#at[:,:,:,:]=np.array([[t[0],t[0]],[t[1],t[1]]])
#at

ok(b).T


array([[[ 0.54030231,  0.54030231],
        [10.        , 10.        ]],

       [[ 0.54030231,  0.54030231],
        [ 6.        ,  6.        ]]])

In [260]:
a = np.arange(3)
b=np.arange(3)
c = np.concatenate((a,b))
c

array([0, 1, 2, 0, 1, 2])

In [98]:
l = np.apply_along_axis(ok, 1, k)
l[1,:,:]

array([[ 0.54030231,  0.54030231],
       [60.        , 60.        ]])

In [77]:
%%timeit
zip(a,b)

The slowest run took 7.23 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.11 µs per loop


In [261]:
a=np.array([1.0,2.0]).astype(int)
a

array([1, 2])

In [16]:
elapsed_time(v_TransformField(C, alpha, beta, flag))

IndexError: invalid index to scalar variable.

In [110]:
 Sx = np.array([])

Sx = C[:,0]
Sx

array([1, 0])

In [113]:
test=[[1,2,3],[8,2]]
test[1][0]

8

# function 2

In [ ]:
def FindCycle(startTime,endTime,Step):
    frames_of_Cycle = []
    #frame_range = range(0,len(Step.frames))
    for frame in Step.frames:
        if (frame.frameValue >= startTime) and (frame.frameValue <= endTime):
           frames_of_Cycle.append(frame)
        elif (frame.frameValue > endTime):
             break
    
    return frames_of_Cycle

# function 3

In [ ]:
def FindCycle2(frames, Step):
    frames_of_Cycle = []
    #frame_range = range(0,len(Step.frames))
    for i in frames:
        frames_of_Cycle.append(Step.frames[i])
    #end for  
    return frames_of_Cycle

# function 4

In [115]:
def newSWT(ALPHA,BETA,frames,E_Modul):
    aM = 0.35e-3
    bM = -0.1
    SWT_Table = np.array([])
    EL_RANGE = np.array(i_element_id)
    for element_id in EL_RANGE:
        oldStress_Table = np.array([])###
        oldStrain_Table = np.array([])###
        for frame in frames:
            stressN = frame.fieldOutputs['S'].getSubset(position=CENTROID).values[element_id]
            strainN = frame.fieldOutputs[strain_label].getSubset(position=CENTROID).values[element_id]

            stressTemp = np.zeros(6) ###
            strainTemp = np.zeros(6) ###

            stressN_data = np.array(stressN.data)

            '''test'''
            print(stressN_data.shape)

            stressTemp[:] = stressN_data[:]
            strainTemp[:] = strainN_data[:]

            oldStress_Table = np.append(oldStress_Table,stressTemp)###
            oldStrain_Table = np.append(oldStrain_Table,strainTemp)###

        oldStress_Table = oldStress_Table.reshape(len(frames),6)###
        oldStrain_Table = oldStrain_Table.reshape(len(frames),6)###

        for beta in BETA:
            for alpha in ALPHA:############
                newStress_Table = np.array([])
                newStrain_Table = np.array([])

                newStress_Table =  TransformField(oldStress_Table,abaqus.degreeToRadian(alpha),abaqus.degreeToRadian(beta),'')
                newStrain_Table =  TransformField(oldStrain_Table,abaqus.degreeToRadian(alpha),abaqus.degreeToRadian(beta),'strain')

                # Poisk max Sx, Ex i min Ex
                Sx = np.array([])
                Ex = np.array([])

                Sx = newStress_Table[:,0]### ??? -->0 use frame 0
                Ex = newStrain_Table[:,0]###

                Smax = np.max(Sx)
                Smin = np.min(Sx)
                Sm = 0.5*(Smax+Smin)
                Sa = 0.5*(Smax-Smin)

                Emax = np.max(Ex)
                Emin = np.min(Ex)
                Msig = aM * Rm + bM
                if Sm >= 0:
                   Km = Msig * (2.+Msig)
                else:
                   Km = Msig/3. * (2.+Msig/3.)
                if ((Sa+Km*Sm) >= 0):
                   SWT = (Sa+Km*Sm)*(Emax-Emin)/2.0*E_Modul
                else:
                   SWT = 0.0
                # frame.fieldOutputs['S'].values[element_id].integrationPoint,

                SWT_Table =np.append(SWT_Table,np.array([frame.fieldOutputs['S'].getSubset(position=CENTROID).values[element_id].elementLabel,alpha,beta,SWT]))


        print(float(EL_RANGE.index(element_id))/len(EL_RANGE)*100.0)
    SWT_Table = SWT_Table.reshape(len(BETA)*len(ALPHA)*len(EL_RANGE),4)###

    return SWT_Table

## test

In [146]:
def newSWT(ALPHA,BETA,E_Modul):
    aM = 0.35e-3
    bM = -0.1
    SWT_Table = np.array([])
    EL_RANGE = np.arange(3)
    for element_id in EL_RANGE:
        oldStress_Table = np.ones(24)*element_id###
        oldStrain_Table = np.ones(24)*element_id###

        oldStress_Table = oldStress_Table.reshape(4,6)###
        oldStrain_Table = oldStrain_Table.reshape(4,6)###

        for beta in BETA:
            for alpha in ALPHA:############
                newStress_Table = np.array([])
                newStrain_Table = np.array([])

                newStress_Table =  TransformField(oldStress_Table,alpha,beta,'')
                newStrain_Table =  TransformField(oldStrain_Table,alpha,beta,'strain')

                # Poisk max Sx, Ex i min Ex
                Sx = np.array([])
                Ex = np.array([])

                Sx = newStress_Table[:,0]### ??? -->0 use frame 0
                Ex = newStrain_Table[:,0]###

                Smax = np.max(Sx)
                Smin = np.min(Sx)
                Sm = 0.5*(Smax+Smin)
                Sa = 0.5*(Smax-Smin)

                Emax = np.max(Ex)
                Emin = np.min(Ex)
                Msig = aM * Rm + bM
                if Sm >= 0:
                   Km = Msig * (2.+Msig)
                else:
                   Km = Msig/3. * (2.+Msig/3.)
                if ((Sa+Km*Sm) >= 0):
                   SWT = (Sa+Km*Sm)*(Emax-Emin)/2.0*E_Modul
                else:
                   SWT = 0.0
                # frame.fieldOutputs['S'].values[element_id].integrationPoint,

                SWT_Table = np.append(SWT_Table,np.array([alpha,beta,SWT]))
    SWT_Table = SWT_Table.reshape((len(BETA)*len(ALPHA)*3,3))###
    print('ok')

    return SWT_Table

In [147]:
ALPHA = np.array([10,20])
BETA = np.array([10,20])+12

E_Modul = 2.0e5
k = 0.4
Syield = 885.88 #[MPa]
Rm = 1046.23 #[MPa]



In [149]:
%%time
newSWT(ALPHA,BETA,E_Modul)#.reshape(:,3)

ok
Wall time: 0 ns


array([[10., 22.,  0.],
       [20., 22.,  0.],
       [10., 32.,  0.],
       [20., 32.,  0.],
       [10., 22.,  0.],
       [20., 22.,  0.],
       [10., 32.,  0.],
       [20., 32.,  0.],
       [10., 22.,  0.],
       [20., 22.,  0.],
       [10., 32.,  0.],
       [20., 32.,  0.]])

In [133]:
newSWT(ALPHA,BETA,frames,E_Modul)
#ALPHA = [0, 10, 20, 30, 40, 45, 50,60, 70,80,90,100,110,120,130, 135, 140,150,160,170]
ALPHA = np.arange(0,185,5)
#BETA = [0, 10, 20, 30, 40, 50,60, 70,80,90,100,110,120,130,140,150,160,170]
BETA = np.arange(0,185,5)

NameError: name 'frames' is not defined

In [30]:
a = np.zeros(6)
c=np.array([])
c =np.append(c,a)
c 

array([0., 0., 0., 0., 0., 0.])

In [31]:
c =np.append(c,a)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
c.reshape(2,6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [43]:
def vect(a,c):
    k=a*c
    return k

In [45]:
vect(a+2,a+1)

array([2., 2., 2., 2., 2., 2.])

In [40]:
a

array([0., 0., 0., 0., 0., 0.])

In [49]:
np.array(a)
range(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
a = a+1
c =c.reshape(2,6)+2

In [82]:
#o = np.dot(c,a.T)
a = []


In [89]:
c=[1,2]*2
a.append([1,2,6])
print(a)

[1, 2, 2, [1], [1, 2], [1, 2], [1, 2, 6]]


In [100]:
c
c =np.sort(c)
np.max(c)


2

In [104]:
print(float(1)/2*100.0)

50.0


In [166]:
alpha=beta = np.arange(0,185,5)
alpha

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180])

In [171]:
xx, yy = np.meshgrid(beta, alpha)
a =yy.ravel()
b=xx.ravel()
b,a

(array([  0,   5,  10, ..., 170, 175, 180]),
 array([  0,   0,   0, ..., 180, 180, 180]))

# function 5

In [ ]:
def export_results(data, fileName='SWT_results.tab'):
    file = open(''+fileName,'w+')
    for line in range(0,len(data)):
        file.write(str(data[line][0])+', '+str(data[line][1])+', '+str(data[line][2])+', '+str(data[line][3])+', '+format(data[line][4], '1.6f')+chr(10))
    
    file.close()
    return

# function 6

In [ ]:
def FatemiSocie(ALPHA,BETA,frames,k,Syield):

	FS_Table = np.array([])
	EL_RANGE = i_element_id
	for element_id in EL_RANGE:
		oldStress_Table = np.array([])
		oldStrain_Table = np.array([])
		for frame in frames:
			stressN = frame.fieldOutputs['S'].getSubset(position=CENTROID).values[element_id]
			strainN = frame.fieldOutputs[strain_label].getSubset(position=CENTROID).values[element_id]
			
			stressTemp = np.zeros(6) ###
			strainTemp = np.zeros(6) ###
			
			stressN_data = np.array(stressN.data)
			strainN_data = np.array(strainN.data)

			stressTemp[:] = stressN_data[:]
			strainTemp[:] = strainN_data[:]

			oldStress_Table = np.append(oldStress_Table,stressTemp)###
			oldStrain_Table = np.append(oldStrain_Table,strainTemp)###

		oldStress_Table = oldStress_Table.reshape(len(frames),6)###
		oldStrain_Table = oldStrain_Table.reshape(len(frames),6)###

		#FS_Table = []
		for alpha,beta in zip(ALPHA,BETA):

			newStress_Table = np.array([])
			newStrain_Table = np.array([])
			
			newStress_Table =  TransformField(oldStress_Table,abaqus.degreeToRadian(alpha),abaqus.degreeToRadian(beta),'')
			newStrain_Table =  TransformField(oldStrain_Table,abaqus.degreeToRadian(alpha),abaqus.degreeToRadian(beta),'strain')
			
			# Poisk max Sx, Ex i min Ex
			Sx = np.array([])
			Exy = np.array([])
			Ezx = np.array([])
		
			Sx = newStress_Table[:,0]
			Exy = newStrain_Table[:,3]
			Ezx = newStrain_Table[:,5]

			Smax = np.max(Sx)
			Emax = np.max(Exy)
			Emin = np.min(Exy)
			E2max = np.max(Ezx)
			E2min = np.min(Ezx)
			
			if ((E2max-E2min)>(Emax-Emin)):
			   Emax = E2max
			   Emin = E2min
			
			FS = 0.5*(Emax - Emin)*(1 + k*Smax/Syield)

			FS_Table =np.append(FS_Table,np.array([frame.fieldOutputs['S'].getSubset(position=CENTROID).values[element_id].elementLabel,alpha,beta,FS]))

		print(float(EL_RANGE.index(element_id))/len(EL_RANGE)*100.0)
	FS_Table = FS_Table.reshape(len(BETA)*len(EL_RANGE),4)

	return FS_Table

# function 7

# function 8

# function 9

# function 10